
/**
 * A unique version number generator for any state that is generated by the
 * local node.
 */

public class VersionGenerator
{
    private static final AtomicInteger version = new AtomicInteger(0);

    public static int getNextVersion()
    {
        return version.incrementAndGet();
    }
}
